name: CI
on:
  push:
    branches: [ develop ]
jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Push code to develop Gitlab
        env:
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITLAB_REPOSITORY_URL: ${{ secrets.GITLAB_REPOSITORY_URL }}
        run: |
          echo "Starting to push repo to gitlab"
          git remote add gitlab "https://oauth2:${GITLAB_ACCESS_TOKEN}@${GITLAB_REPOSITORY_URL}"
          git push gitlab develop
          
  # build_docker_image:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Build Docker image
  #       env:
  #         IMAGE_NAME: softbank-mentari
  #         IMAGE_TAG: develop
  #       run: |
  #         echo "Building Docker image..."
  #         docker build -t $IMAGE_NAME:$IMAGE_TAG .
  #
  #     - name: Save Docker image to file
  #       run: |
  #         docker save softbank-mentari:develop -o image.tar
  #         ls -lh *.tar
  #
  #     - name: Upload image artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: docker-image
  #         path: image.tar
  #         retention-days: 1
  #
  # push_to_acr:
  #   runs-on: ubuntu-latest
  #   needs: build_docker_image
  #   steps:
  #     - name: Download image artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: docker-image
  #
  #     - name: Verify downloaded files
  #       run: |
  #         ls -lh
  #
  #     - name: Load Docker images
  #       run: |
  #         docker load -i image.tar
  #         docker images
  #
  #     - name: Login to Azure Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
  #         username: ${{ secrets.ACR_USERNAME }}
  #         password: ${{ secrets.ACR_PASSWORD }}
  #
  #     - name: Tag and push to ACR
  #       env:
  #         ACR_REGISTRY: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
  #         IMAGE_NAME: softbank-mentari
  #       run: |
  #         docker tag softbank-mentari:develop $ACR_REGISTRY/$IMAGE_NAME:develop
  #
  #         echo "Pushing images to ACR..."
  #         docker push $ACR_REGISTRY/$IMAGE_NAME:develop
  #
  #     - name: Push success
  #       run: |
  #         echo "Images pushed successfully!"
  #         echo "Saved at: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/softbank-mentari:develop"
