name: CI

on:
  push:
    branches: [ develop ]

jobs:
  push_to_gitlab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push code to develop Gitlab
        env:
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_EMAIL: ${{ secrets.GITLAB_EMAIL }}
          GITLAB_REPOSITORY_URL: ${{ secrets.GITLAB_REPOSITORY_URL }}
        run: |
          echo Starting to push repo to gitlab
          git config user.name "${GITLAB_USERNAME}"
          git config user.email "${GITLAB_EMAIL}"
          GITLAB_URL="https://oauth2:${GITLAB_ACCESS_TOKEN}@${GITLAB_REPOSITORY_URL}"
          
          git remote add gitlab "${GITLAB_URL}"
          git push gitlab develop

